### ISSUE TITLE
Issues about "Free Lunch for Generating Effective Outlier Supervision"

### ISSUE THREAD

**Issue by gugite** [ForeverPs/BAL#2]
Hi, I am very curious about this work recently published on Arxiv, which is much similar to some existing work.

Could you please tell me when you started doing this work? 

How long did you think about the idea and finish the work?

**Comment by ForeverPs** [comment]
The code is finished before 2022/10/28 since this is the last modified record we can trace. A small part of the training and testing data are collected before 2022/09/21, while the others come from our long-stored disk. The idea is constructed and verified at about the middle year of 2022, i.e., 2022/05~2022/06. We started writing the paper about two months ago, and the last modified time shown on Overleaf was about 14 days before.

You mentioned that this work is "much similar" to previous work. We conduct a thorough survey before doing this job, noticing no previous similar study. If you find such work, we would appreciate it if you could share the links with us, and we will check your statement carefully and strictly.

**Comment by gugite** [comment]
Hi, thank you so much for your kind reply. I believe that this is just an idea crash now. 

Honestly, when I came across this paper, I found that ideas, theoretical analyses, and technical details were almost the same as our work rejected by ECCV22. Your reply has addressed my concerns and issues. Thanks!

By the way, it is very interesting to come up with the same idea. Such a coincidence, lol !

You can delete this issue if necessary since it isn't related to this repository. Sorry for bothering you.
